services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=habita_recife_backend'
      - 'MYSQL_ROOT_PASSWORD=Admin2'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_PASSWORD=Admin1'
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
